version: '2'
services:
  eureka:
    image: springcloud/eureka:latest
    container_name: eureka
    hostname: eureka
    ports:
     - "8761:8761"
  supplyservice:
    image: tusla/supplyservice:concept4
    container_name: supplyservice
    hostname: supplyservice
    ports:
     - "8081:8081"
    environment:
      PROFILE: "docker"
      SERVER_PORT: "8081"
  stockservice:
    image: tusla/stockservice:concept4
    container_name: stockservice
    hostname: stockservice
    ports:
      - "8080:8080"
    environment:
      PROFILE: "docker"
      SERVER_PORT: "8080"
      EUREKASERVER_PORT: "8761"
      SUPPLYSERVICE_PORT: "8081"